### ISSUE TITLE
Weird box beside check issue

### ISSUE THREAD

**Issue by Braunson** [mikeerickson/phpunit-pretty-result-printer#149]
Just updated to latest, now when running tests there's a box that appears beside each check icon..

See http://bit.ly/2OHxMJy

SSHing into Homestead via SmarTTY on Win 10, didn't have this issue previously.

**Comment by mikeerickson** [comment]
Hmmm, curious. It is some escape character for sure. I have a few ideas, but will take a closer look using your environment.

**Comment by mikeerickson** [comment]
@Braunson Does this happen with other icons, or is it just pass?

Can you please try editing the `phpunit-printer.yml` file and change the marker for `cd-pass` and see what happens.  

In addition, try remove all the whitespace in this file as well and test.  I am curious if there is something in the whitespace that is being identitied on your homestead vm.

```yml
options:
  cd-printer-hide-class: false
  cd-printer-simple-output: false
  cd-printer-show-config: true
  cd-printer-hide-namespace: true
  cd-printer-anybar: false
  cd-printer-anybar-port: 1738
markers:
  cd-pass: "✔︎ " 
  cd-fail: "✖ "
  cd-error: "⚈ "
  cd-skipped: "=> "
  cd-incomplete: "∅ "
  cd-risky: "⌽ "
```

**Comment by mikeerickson** [comment]
What version of OS (assuming Ubuntu) and PHPUnit are you using. 

I have tested across all our test environments (various versions of Ubuntu and PHPUnit) using docker and I am not seeing the box character

**Comment by mikeerickson** [comment]
@Braunson In the latest version, the pass icon is different that previous builds.  Here is what they used to use if you would like to take this `cd-pass` icon and place in your local `phpunit-printer.yml` 

```yml
...
markers:
  cd-pass: "✓ "
  cd-fail: "✖ "
  cd-error: "⚈ "
  cd-skipped: "=> "
  cd-incomplete: "∅ "
  cd-risky: "⌽ "
...
```
